// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://lvlsisdftrouwzlaprtq.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2bHNpc2RmdHJvdXd6bGFwcnRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzMzNDY4MzMsImV4cCI6MjA0ODkyMjgzM30.10Y5tObcAQlRPkFoRJR6Ij6-nASkhsK5YW9ZWhSU9CE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);