// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://ikvulknnclhhzxvppssc.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlrdnVsa25uY2xoaHp4dnBwc3NjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzMzNDE2ODEsImV4cCI6MjA0ODkxNzY4MX0.wOiSYy8xRd9gedRk1xJIdHw9DmMkaBbFOpOG8GDB_LY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);